name: Contracts CI

on:
  push:
    paths:
      - "contracts/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "contracts/**"
      - ".github/workflows/**"

jobs:
  contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: npm ci
      - run: npm run build --workspace=contracts
      - name: Check formatting and linting of JS/TS in contracts
        run: npm run check ./contracts
      - name: Lint Solidity in contracts
        run: npm run lint:sol --workspace=contracts
      - name: Check Solidity formatting
        run: npm run format:sol --workspace=contracts -- --check
      - run: npm run test --workspace=contracts
